version: "3.9"

services:
  db:
    image: postgres:16
    container_name: earthquake_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: ./app
    container_name: earthquake_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: uvicorn api:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
